### ISSUE TITLE
KMM crashes everytime with "Profile configuration hasn't been loaded" when game is on a samba share

### ISSUE THREAD

**Issue by tornadox** [KerberX/Kortex-Mod-Manager#14]
KMM 2.0 crashes every time when I try to use it on any of my PCs. The game is located on a samba share (fallout 4)

**Comment by KerberX** [comment]
@tornadox 
Can you describe KMM install sequence in detail? Also, upload the latest log file (`%LocalAppData%\KortexModManager\Logs`)?

**Comment by tornadox** [comment]
`15:28:55: Kortex Mod Manager v2.0: Log opened
15:28:55: SystemApplication::OnInit
15:28:55: System: Windows 10 x64 . Kernel version: 10.0
15:28:55: Another instance detected: false
15:28:55: Root folder: C:\Users\Razer\OneDrive\Downloads\Kortex 2.0a7-90868-2-0a7-1566683895
15:28:55: Data folder: C:\Users\Razer\OneDrive\Downloads\Kortex 2.0a7-90868-2-0a7-1566683895\Data
15:28:55: Logs folder: C:\Users\Razer\AppData\Local\KortexModManager\Logs
15:28:55: User settings folder: C:\Users\Razer\AppData\Local\KortexModManager
15:28:55: User settings file: C:\Users\Razer\AppData\Local\KortexModManager\Settings.xml
15:28:55: Instances folder: C:\Users\Razer\AppData\Local\KortexModManager\Instances
15:28:55: SystemApplication::LoadGlobalConfig
15:28:55: SystemApplication::LoadGlobalConfig -> false
15:28:55: SystemApplication::InitComponents
15:28:55: Trying to load translation from file "C:\Users\Razer\OneDrive\Downloads\Kortex 2.0a7-90868-2-0a7-1566683895\Data\Translation\en-US.Application.xml" for "en-US" component
15:28:55: Warning: iCCP: known incorrect sRGB profile
15:28:55: Warning: iCCP: known incorrect sRGB profile
15:28:55: Warning: iCCP: known incorrect sRGB profile
15:28:55: Begin initializing core systems
15:28:55: Initializing app settings
15:28:55: Pre start config needed
15:29:16: Instances folder changed: C:\Users\Razer\OneDrive\Documents\Kortex
15:29:16: Settings initialized. Begin loading profile.
15:29:16: Core systems initialized
15:29:16: Initializing instances
15:29:16: Instance: 
15:29:16: Trying load instance. InstanceID: 
15:29:16: Unable to load saved instance. Asking user to choose one.
15:29:16: Error: Couldn't retrieve information about list control item -1.
15:29:16: Error: Couldn't retrieve information about list control item -1.
15:29:20: Error: Couldn't retrieve information about list control item -1.
15:29:20: Error: Couldn't retrieve information about list control item -1.
15:29:21: Error: Couldn't retrieve information about list control item -1.
15:29:49: New InstanceID: Fallout 4
15:29:49: Trying again
15:29:49: Trying load instance. InstanceID: Fallout 4
15:29:49: SystemApplication::OnError
15:29:49: An error occurred:

Profile configuration hasn't been loaded. Unable to continue.
15:29:52: SystemApplication::OnExit
15:29:52: Exiting before initialization is completed
15:29:52: Exit code: 6002
15:29:52: SystemApplication::UninitComponents
15:29:52: SystemApplication::SaveGlobalConfig
15:29:52: SystemApplication::SaveGlobalConfig -> true
15:29:52: SystemApplication::TerminateActiveInstance
15:29:52: SystemApplication::TerminateActiveInstance -> Destroying active instance
15:29:52: Log closed
`

**Comment by KerberX** [comment]
Is it a new instance and/or profile created by this installation or it's old instance/profile from v1.x? Anyway, zip and upload your `C:\Users\Razer\AppData\Local\KortexModManager\Instances\Fallout 4` folder (if it's not big).

**Comment by tornadox** [comment]
1) it's a new instance
2) it has only one file Instance.xml, rest is empty

<?xml version="1.0" encoding="utf-8"?>
<Instance GameID="Fallout4">
	<Variables>
		<Entry ID="ActualGameDir" Type="FSPath">\\OMV-MARS\united-share\mediadata\games\Fallout 4</Entry>
	</Variables>
</Instance>

**Comment by KerberX** [comment]
Maybe UNC path aren't supported. I've never tested them. Create a network drive from that path and try again.

**Comment by tornadox** [comment]
It works, thanks!
